[package]
name = "parakeet-crypto"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "parakeet_cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# https://github.com/johnthagen/min-sized-rust
lto = true
strip = true
codegen-units = 1

[dev-dependencies]
pretty-hex = "0.3.0"

[dependencies]
argh = "0.1.9"
byteorder = "1.4.3"
base64 = "0.21.0"
tc_tea = "0.1.4"
md-5 = "0.10.5"
hex = "0.4.3"
thiserror = "1.0"
itertools = "0.10.5"
