name: Rust (Release Build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04", "windows-2022"]

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
