name: Rust (Build & Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04", "windows-2022"]

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v3
    - name: Attempt to build (debug)
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
